on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: yarn install
        run: npm install
      - name: custom_workflow_step
        uses: K-Sato1995/webpack-bundle-analyzer-action@develop
        with:
          webpack-config-path: "webpack.config"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          report-file-name: "report/index.html"
      - name: check files
        run: ls -a
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./analyzeOutput
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
